/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.PaymentDetails;

import control.ControlData;
import control.ControlSeats;
import javax.swing.JTextField;
import model.theater_seats.TheaterSeat;
import view.SeatFrame.SeatFrame;

/**
 *
 * @author adrianealtiche
 */
public class PaymentDetails extends javax.swing.JFrame {

    int totalPrice;
    
    /**
     * Creates new form PaymentDetails
     */
    public PaymentDetails() {
        initComponents();
        uLabel2.scale();
    }

    public void updateFrame()
    {
        ControlSeats ctrlSeat = ControlSeats.getInstance();
        TheaterSeat tSeat = ctrlSeat.getCurrTheaterSeat();
        
        titleLabel.setText(tSeat.getMovieTitle());
        dateLabel.setText(tSeat.getDate());
        timeLabel.setText(tSeat.getTime());
        
        //price
        SeatFrame seatFrame = (SeatFrame) ControlData.getInstance().getFrameByName("SeatFrame");
        String seatSelected = seatFrame.getTFieldText();
        int seatCount = seatSelected.split(",").length - 1;
        
        
        String priceComp = seatCount + " x 350.00 PhP";
        priceLabel.setText(priceComp);
        
        //total price
        totalPrice = seatCount * 350;
        
        totalPriceLabel.setText("TOTAL PRICE: " + totalPrice + ".00 Php");
        
        //seats selected
        seatsSelectedLabel.setText(seatFrame.getTFieldText());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalPriceLabel = new javax.swing.JLabel();
        nameTField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        phoneTField = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        seatsSelectedLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        uLabel2 = new view_components.ULabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        priceLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(11, 0, 26));
        jPanel2.setForeground(new java.awt.Color(11, 0, 26));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fill-up Details");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, 290, 120));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PaymentDetails/seeblackpaymentdet.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 10, 340, 130));

        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(237, 58, 133)));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 1050, 70));

        jLabel7.setFont(new java.awt.Font("YuGothic", 1, 52)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(225, 225, 225));
        jLabel7.setText("PAYMENT DETAILS");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 560, 80));

        totalPriceLabel.setFont(new java.awt.Font("YuGothic", 1, 18)); // NOI18N
        totalPriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalPriceLabel.setText("TOTAL PRICE: 1,200.00 Php");
        totalPriceLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(totalPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, 250, 60));

        nameTField.setText("Name");
        nameTField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTFieldFocusLost(evt);
            }
        });
        jPanel2.add(nameTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, 330, 30));

        jLabel21.setFont(new java.awt.Font("YuGothic", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("PAYMENT DETAILS");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 270, 60));

        titleLabel.setFont(new java.awt.Font("YuGothic", 0, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("AVENGERS: END GAME");
        jPanel2.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 360, 60));

        phoneTField.setText("Phone Number");
        phoneTField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneTFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneTFieldFocusLost(evt);
            }
        });
        jPanel2.add(phoneTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, 330, 30));

        dateLabel.setFont(new java.awt.Font("YuGothic", 0, 18)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setText("DECEMBER 1, 2023");
        jPanel2.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 250, 60));

        jLabel25.setFont(new java.awt.Font("YuGothic", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("SEENEMA CLUB");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 260, 60));

        timeLabel.setFont(new java.awt.Font("YuGothic", 0, 18)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(255, 255, 255));
        timeLabel.setText("1:45 Researved Seating");
        jPanel2.add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 350, 60));

        jLabel27.setFont(new java.awt.Font("YuGothic", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("TICKET(S)");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 100, 60));

        seatsSelectedLabel.setFont(new java.awt.Font("YuGothic", 0, 18)); // NOI18N
        seatsSelectedLabel.setForeground(new java.awt.Color(255, 255, 255));
        seatsSelectedLabel.setText("A11, A12, A13");
        seatsSelectedLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(seatsSelectedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 380, 60));

        priceLabel.setFont(new java.awt.Font("YuGothic", 0, 18)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(255, 255, 255));
        priceLabel.setText("3x 1,200.00 Php");
        jPanel2.add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 200, 60));
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 300, 5));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 300, 5));
        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, 300, 5));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PaymentDetails/holderplace.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, -120, -1, -1));

        uLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proceedToGcash.png"))); // NOI18N
        uLabel2.setDestFrame("Gcash");
        jPanel2.add(uLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 500, 280, -1));
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, 300, 5));
        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 300, 5));
        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 300, 5));

        priceLabel1.setFont(new java.awt.Font("YuGothic", 0, 18)); // NOI18N
        priceLabel1.setForeground(new java.awt.Color(255, 255, 255));
        priceLabel1.setText("3x 1,200.00 Php");
        jPanel2.add(priceLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 200, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTFieldFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_nameTFieldFocusGained
    {//GEN-HEADEREND:event_nameTFieldFocusGained
        JTextField textField = (JTextField) evt.getSource();
    
        // Check if the mouse click occurred on the JTextField
        if (textField.getText().equals("Name")) 
        {
            // Clear the text when the JTextField is clicked
            textField.setText("");
        }
    }//GEN-LAST:event_nameTFieldFocusGained

    private void nameTFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_nameTFieldFocusLost
    {//GEN-HEADEREND:event_nameTFieldFocusLost
        JTextField textField = (JTextField) evt.getSource();
                if (textField.getText().trim().isEmpty()) 
                {
                    textField.setText("Name");
                }
    }//GEN-LAST:event_nameTFieldFocusLost

    private void phoneTFieldFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_phoneTFieldFocusGained
    {//GEN-HEADEREND:event_phoneTFieldFocusGained
        JTextField textField = (JTextField) evt.getSource();
    
        // Check if the mouse click occurred on the JTextField
        if (textField.getText().equals("Phone Number")) 
        {
            // Clear the text when the JTextField is clicked
            textField.setText("");
        }
    }//GEN-LAST:event_phoneTFieldFocusGained

    private void phoneTFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_phoneTFieldFocusLost
    {//GEN-HEADEREND:event_phoneTFieldFocusLost
        JTextField textField = (JTextField) evt.getSource();
                if (textField.getText().trim().isEmpty()) 
                {
                    textField.setText("Phone Number");
                }
    }//GEN-LAST:event_phoneTFieldFocusLost

    public int getTotalPrice()
    {
        return totalPrice;
    }

    
    public String getNameVal()
    {
        return nameTField.getText();
    }

    public String getPhoneVal()
    {
        return phoneTField.getText();
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField nameTField;
    private javax.swing.JTextField phoneTField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceLabel1;
    private javax.swing.JLabel seatsSelectedLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel totalPriceLabel;
    private view_components.ULabel uLabel2;
    // End of variables declaration//GEN-END:variables
}
