package view.SeatFrame;

import control.ControlSeats;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.theater_seats.Seat;
import model.theater_seats.Seats;
import model.theater_seats.TheaterSeat;
import view_components.ScaleableLabel;
import view_components.USeat;

/**
 *
 * @author Salti
 */
public class SeatFrame2 extends javax.swing.JFrame
{
    private JLabel uSeat2;
    private JPanel seatPanel;
    
    /**
     * Creates new form SeatFrame
     */
    
    //25, 35
    public SeatFrame2()
    {
        Dimension seatPanelDimension = new Dimension(USeat.imageWidth * Seats.rows, USeat.imageHeight * Seats.cols);
        
        seatPanel = new JPanel(new GridLayout(Seats.rows, Seats.cols, 5, 5));
//        seatPanel.setSize(USeat.imageWidth * Seats.rows, USeat.imageHeight * Seats.cols);
//        seatPanel.setPreferredSize(seatPanelDimension);
//        
        
        
        this.add(seatPanel);
        this.setSize(800, 600);
        
        //init Seats
        ControlSeats ctrlSeats = ControlSeats.getInstance();
        TheaterSeat tSeatCurr = ctrlSeats.getCurrTheaterSeat();
        TheaterSeat tSeat = ctrlSeats.getTheaterSeats().getTheaterSeat(tSeatCurr);   //reference for the Model.TheaterSeat
        
        Seats seats = tSeat.getSeats();
        ArrayList<ArrayList<Seat>> seatArray = seats.getSeats();
        ArrayList<ArrayList<USeat>> uSeatArray = new ArrayList<>();
        
        for (int x = 0; x < seatArray.size(); ++x)
        {
            ArrayList<Seat> seatTempArray = seatArray.get(x);
            ArrayList<USeat> uSeatTempArray = new ArrayList<>();
            for (int y = 0; y < seatTempArray.size(); ++y)
            {
                Seat seatTemp = seatTempArray.get(y);
                uSeatTempArray.add(new USeat());
                USeat uSeatTemp = uSeatTempArray.get(y);
                
                Dimension seatDimension = new Dimension(USeat.imageWidth, USeat.imageHeight);
                uSeatTemp.setPreferredSize(seatDimension);
                uSeatTemp.setSize(USeat.imageWidth, USeat.imageHeight);
                uSeatTemp.setIcon(new ImageIcon("src/main/resources/SeatFrame/seat_available.png"));
                uSeatTemp.scale();
                
                uSeatTemp.setSeat(seatTemp);
                seatPanel.add(uSeatTempArray.get(y));
            }
            
            uSeatArray.add(uSeatTempArray);
        }
        
                
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
