/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Receipt;

import control.ControlData;
import control.ControlSeats;
import model.theater_seats.TheaterSeat;
import model.theater_seats.TheaterSeats;
import view.PaymentDetails.PaymentDetails;

/**
 *
 * @author adrianealtiche
 */
public class Receipt extends javax.swing.JFrame {

    /**
     * Creates new form Receipt
     */
    public Receipt() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false); // Disable resize frame
        
    }

    public void updateFrame()
    {
        PaymentDetails currFrame = (PaymentDetails) ControlData.getInstance().getFrameByName("PaymentDetails");
        
        nameLabel.setText(currFrame.getNameVal());
        numberLabel.setText(currFrame.getPhoneVal());
        
        
        TheaterSeat currSeat = ControlSeats.getInstance().getCurrTheaterSeat();
        String dateTime = currSeat.getDate() + " " + currSeat.getTime();
        dateTimeLabel.setText(dateTime);
        
        priceLabel.setText(String.valueOf(currFrame.getTotalPrice()));
        paidPriceLabel.setText(String.valueOf(currFrame.getTotalPrice()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        paidPriceLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        dateTimeLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        traceNumLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        numberLabel = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        uLabel1 = new view_components.ULabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(11, 0, 26));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paidPriceLabel.setFont(new java.awt.Font("Yu Gothic Light", 0, 36)); // NOI18N
        paidPriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(paidPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 353, 210, 60));

        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(237, 58, 133)));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 1050, 70));

        jLabel7.setFont(new java.awt.Font("YuGothic", 1, 52)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(225, 225, 225));
        jLabel7.setText("RECEIPT");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 560, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Receipt/seeblackreceiptpng.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 10, 340, 130));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("₱");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 350, 40, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic Light", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PAID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, 130, 90));

        jLabel9.setFont(new java.awt.Font("YuGothic", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PAYMENT DETAILS");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 360, 80));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, 260, 10));

        dateTimeLabel.setFont(new java.awt.Font("YuGothic", 1, 18)); // NOI18N
        dateTimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateTimeLabel.setText("NOVEMBER 20, 2023 7:42 AM");
        jPanel1.add(dateTimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, -1, 70));

        jLabel15.setFont(new java.awt.Font("YuGothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("SEENEMA");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 255, 220, 70));

        jLabel16.setFont(new java.awt.Font("YuGothic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Gcash");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 180, 70));

        priceLabel.setFont(new java.awt.Font("YuGothic", 1, 18)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(255, 255, 255));
        priceLabel.setText("₱ 1,200.00 ");
        jPanel1.add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 220, 70));

        traceNumLabel.setFont(new java.awt.Font("YuGothic", 1, 18)); // NOI18N
        traceNumLabel.setForeground(new java.awt.Color(255, 255, 255));
        traceNumLabel.setText("TRS0922711168999");
        jPanel1.add(traceNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 290, 70));

        jLabel19.setFont(new java.awt.Font("YuGothic", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("711911");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 180, 70));

        jLabel20.setFont(new java.awt.Font("YuGothic", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("TO:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 40, 20));

        jLabel21.setFont(new java.awt.Font("YuGothic", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("FROM:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 60, 30));

        nameLabel.setFont(new java.awt.Font("YuGothic", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("MYCHAL P***** ");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 360, 70));

        numberLabel.setFont(new java.awt.Font("YuGothic", 1, 18)); // NOI18N
        numberLabel.setForeground(new java.awt.Color(255, 255, 255));
        numberLabel.setText("09* **** 0711 ");
        jPanel1.add(numberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 240, 70));

        jLabel24.setFont(new java.awt.Font("YuGothic", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("TOTAL:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, 20));

        jLabel25.setFont(new java.awt.Font("YuGothic", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("REFERENCE NO.:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 460, 160, 20));

        jLabel26.setFont(new java.awt.Font("YuGothic", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("TRACE ID:");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 481, 100, 30));

        jLabel27.setFont(new java.awt.Font("YuGothic", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("DATE:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 515, 60, 20));

        uLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backtoHome.png"))); // NOI18N
        uLabel1.setDestFrame("HomePage");
        jPanel1.add(uLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 440, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Receipt/Box.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 260, 310, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1460, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateTimeLabel;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JLabel paidPriceLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel traceNumLabel;
    private view_components.ULabel uLabel1;
    // End of variables declaration//GEN-END:variables
}
