/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.SignUp;

/**
 * 
 * @author adrianealtiche
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        this.setResizable(false); // Disable resize frame
        setLocationRelativeTo(null);
        txtuser.setBackground(new java.awt.Color(0,0,0,1));
        txtpass.setBackground(new java.awt.Color(0,0,0,1));
        txtcp.setBackground(new java.awt.Color(0,0,0,1));
        


        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        txtcp = new javax.swing.JPasswordField();
        txtuser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        uLabel2 = new view_components.ULabel();
        uLabel1 = new view_components.ULabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(51, 10, 52));
        kGradientPanel1.setkGradientFocus(200);
        kGradientPanel1.setkStartColor(new java.awt.Color(11, 0, 26));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcp.setForeground(new java.awt.Color(255, 255, 255));
        txtcp.setText("jPasswordField1");
        txtcp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtcp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txtcp, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 500, 340, 20));

        txtuser.setForeground(new java.awt.Color(255, 255, 255));
        txtuser.setText("username goes here");
        txtuser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, 340, 20));

        jLabel5.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(225, 225, 225));
        jLabel5.setText("CONFIRM PASSWORD");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, -1, -1));

        jLabel1.setFont(new java.awt.Font("YuGothic", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(225, 225, 225));
        jLabel1.setText("Already Have An Account?");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 580, -1, 20));

        jLabel3.setFont(new java.awt.Font("YuGothic", 1, 70)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(225, 225, 225));
        jLabel3.setText("UP");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, -1, 150));

        jLabel4.setFont(new java.awt.Font("YuGothic", 1, 70)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(225, 225, 225));
        jLabel4.setText("SIGN");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, -1, 150));

        jLabel6.setFont(new java.awt.Font("YuGothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(225, 225, 225));
        jLabel6.setText("SIGN-UP");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 550, -1, -1));

        txtpass.setForeground(new java.awt.Color(255, 255, 255));
        txtpass.setText("jPasswordField1");
        txtpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, 340, 20));

        uLabel2.setForeground(new java.awt.Color(237, 58, 133));
        uLabel2.setText("SIGN-IN");
        uLabel2.setFont(new java.awt.Font("YuGothic", 3, 12)); // NOI18N
        kGradientPanel1.add(uLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 600, 60, -1));

        uLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignUp/signupbutton.png"))); // NOI18N
        kGradientPanel1.add(uLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, 490, -1));

        jLabel7.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(225, 225, 225));
        jLabel7.setText("PASSWORD");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, -1, -1));

        jLabel8.setFont(new java.awt.Font("YuGothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(225, 225, 225));
        jLabel8.setText("USERNAME");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 360, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignUp/designdesign.png"))); // NOI18N
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -30, 1420, 750));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JPasswordField txtcp;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    private view_components.ULabel uLabel1;
    private view_components.ULabel uLabel2;
    // End of variables declaration//GEN-END:variables
}
